# This is a basic workflow to help you get started with Actions

name: SyncForkedMasters

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/20 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allows external webhook trigger
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3  
      #  with:
      #    submodules: recursive
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

      # Runs a set of commands using the runners shell
      - name: Synchronize masters
        run: |
          cd $GITHUB_WORKSPACE/releng-scripts/sync-forked-masters
          chmod a+x syn_git_masters.sh
          ./syn_git_masters.sh
