# 
name: SyncSubModulesBranches

on:   
  #schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '*/10 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Sync submodules branches
        run: |
          echo "GITUSER_NAME=${{ secrets.GITUSER_NAME }}" >> $GITHUB_ENV
          echo "GITUSER_PASSWORD=${{ secrets.GITUSER_PASSWORD }}" >> $GITHUB_ENV
          cd releng-scripts/sync-gemoc-submodules
          mvn --batch-mode clean verify
