# This is a basic workflow to help you get started with Actions

name: SyncForkedMaster

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2  
      #  with:
      #    submodules: recursive
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Inspect workspace
        run: |
          pwd 
          ls
          cd $GITHUB_WORKSPACE
          ls

      # Runs a set of commands using the runners shell
      - name: Synchronize masters
        run: |
          cd $GITHUB_WORKSPACE/releng-scripts/sync-forked-masters
          chmod a+x syn_git_masters.sh
          ./syn_git_masters.sh
