# 
name: SyncSubModulesBranches

on:   
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/20 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: SetSSH key
        run: |
          echo $HOME
          ls -lsa $HOME
          echo "${{ secrets.BOT_SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
          chmod og-rw $HOME/.ssh/id_ed25519
          ls -lsa $HOME/.ssh
      - name: Sync submodules branches
        run: |
          export GITUSER_NAME=gemoc-bot
          export GITUSER_PASSWORD=${{ secrets.BOT_GITUSER_PASSWORD }}
          cd releng-scripts/sync-gemoc-submodules
          mvn --batch-mode -Dgituser.email=gemocbot@gmail.com clean verify
